version: '3'

services:
    brevetsapp:
        build: ./brevets_app
        command: python -u flask_brevets.py
        volumes:
            - ./brevets_app:/app
        ports:
            - "5000:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    restapi:
        build: ./api
        command: python -u api.py
        volumes:
            - ./api:/api
        ports:
            - "5001:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    website:
        build: ./website
        command: python -u website.py
        volumes:
            - ./website:/website
        ports:
            - "5002:5000"
        depends_on:
            - restapi
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    ourdb:
        image: mongo:latest